Vagrant.configure("2") do |config|
    config.vm.box      = "ubuntu/trusty64"
    config.vm.hostname = "vm"

    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 2048
        virtualbox.gui    = false
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook       = "../builder/configure.yml"
    end
end
